### ISSUE TITLE
readability of critical alerts

### ISSUE THREAD

**Issue by HaveFun83** [synyx/tuwat#107]
Currently the critical alerts lacks readability as light gray front on red background are harder to read.

Looks like the decrease the opacity within the css can help here:
```diff
.status.red, .status.red summary, .status.red details {
     background-color: #FF4040;
     color: white;
-    opacity: 0.75;
+    opacity: 0.9;   
}
```

**Comment by BuJo** [comment]
Should be fixed with #108, I'll make a new release soon.
