### ISSUE TITLE
Icinga2 connector: acknowledged host still displays individual service problems

### ISSUE THREAD

**Issue by punycode** [synyx/tuwat#228]
If a complete host is acknowledged for existing problems inside Icinga2, `tuwat` still displays individual problems from the Icinga2 services for this host. This is unexpected, since it runs contrary to the Icinga2 default of not showing those individual service problems.

### Expected behaviour

If a host with multiple service problems is acknowledged in Icinga2, `tuwat` should consider those problems as also being acknowledged and therefore not add them to the internal list of problems to display to the user.

**Comment by BuJo** [comment]
This may be an oversight..  the older icinga/nagios allows one to acknowledge purely the host vs. host and services.  I guess that feature is no longer in icinga2.
