### ISSUE TITLE
Highlight the current page in the menu

### ISSUE THREAD

**Issue by contargo-development** [synyx/tuwat#268]
In order to improve the visibility of the currently opened page, it would help if the respective menu item is highlighted.

Maybe one could also change the default link color of the menu items to one with more contrast.

![menu](https://github.com/user-attachments/assets/68a176cc-9dc3-46c5-9360-a3da8c2fd3ad)

Thanks
Joachim (io)
Contargo

**Comment by DerGeras** [comment]
Thanks @contargo-development (io) for the suggestion, you will find the menu more readable in [Release 1.11](https://github.com/synyx/tuwat/releases/tag/v1.11.0)
